### ISSUE TITLE
Drop area detector from iconfig

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/BITS#41]
Now, area detector objects can be declared in `devices.yml`, such as:

```yaml
apstools.devices.ad_creator:

  - name: adsimdet
    # IOC host: arf
    prefix: "ad:"
    labels: ["area_detector", "detectors"]
    plugins:
      - cam:
          class: apstools.devices.SimDetectorCam_V34
      - image
      - pva
      - hdf1:
          class: apstools.devices.AD_EpicsFileNameHDF5Plugin
          # TODO: check these paths
          read_path_template: "/mnt/iocad/tmp/"
          write_path_template: "/tmp/"
      - roi1
      - stats1
```

Suggest we add example above (commented out) to `devices.yml` and remove all _this_ configuration: https://github.com/BCDA-APS/bs_model_instrument/blob/68c5869a01aaa116e53a7e262ca5a07a09a752c3/src/instrument/configs/iconfig.yml#L44-L56
